-- Carta real de Katrina (misma fuente que src/data/menu.ts).
-- Correr DESPUÉS de schema.sql. Si la tabla ya tiene filas, no duplica.

INSERT INTO public.menu_items (category_id, photo_key, name, description, price, price_whole, price_half, sort_order)
SELECT * FROM (VALUES
  ('hamburguesas','Classic Burger','Classic Burger','Lechuga, tomate, huevo, jamón, queso y papas.','$9.000',NULL,NULL,0),
  ('hamburguesas','Doble Burger','Doble Burger','Doble carne, lechuga, tomate, huevo y papas.','$13.000',NULL,NULL,1),
  ('hamburguesas','Katrina Burger','Katrina Burger','Doble carne 150gr, bacon, cheddar, salsa americana, huevo y papas.','$16.000',NULL,NULL,2),
  ('hamburguesas','Baño de Cheddar','Baño de Cheddar','Adicional para cualquier hamburguesa.','$3.000',NULL,NULL,3),
  ('hamburguesas','Bandeja de Hamburguesas','Bandeja de Hamburguesas','Para compartir: varias hamburguesas con papas al centro.','Consultar',NULL,NULL,4),
  ('hamburguesas','Hamburguesas con Panes de Colores','Hamburguesas con Panes de Colores','Panes artesanales de colores realizados por Carmelo.','Consultar',NULL,NULL,5),
  ('pizzas','Pizza Común','Pizza Común',NULL,NULL,'$9.000','$5.000',0),
  ('pizzas','Pizza Especial','Pizza Especial',NULL,NULL,'$11.000','$6.000',1),
  ('pizzas','Pizza Doble Queso','Pizza Doble Queso',NULL,NULL,'$11.000','$6.000',2),
  ('pizzas','Pizza de Pollo','Pizza de Pollo',NULL,NULL,'$15.000','$8.000',3),
  ('pizzas','Pizza Napolitana','Pizza Napolitana',NULL,NULL,'$11.000','$6.000',4),
  ('pizzas','Pizza de Ternera','Pizza de Ternera',NULL,NULL,'$18.000','$10.000',5),
  ('pizzas','Pizza Mexicana','Pizza Mexicana','Picante suave.',NULL,'$18.000','$10.000',6),
  ('sandwiches','Lomito Clásico','Lomito Clásico','Lechuga, tomate, huevo, jamón, queso y papas.','$10.000',NULL,NULL,0),
  ('sandwiches','Lomito Katrina','Lomito Katrina','Bacon, cheddar, salsa americana, huevo y papas.','$15.000',NULL,NULL,1),
  ('sandwiches','Sándwich de Milanesa','Sándwich de Milanesa','Lechuga, tomate, huevo, jamón, queso y papas.','$10.000',NULL,NULL,2),
  ('sandwiches','Milanesa Katrina','Milanesa Katrina','Bacon, cheddar, salsa americana, huevo y papas.','$15.000',NULL,NULL,3),
  ('sandwiches','Especial Katrina','Especial Katrina','Bife de chorizo, cebolla caramelizada, muzarella, morrón asado, mayonesa de ajo y papas.','$18.000',NULL,NULL,4),
  ('sandwiches','Lomo Katrina','Lomo Katrina','Nuestro lomo con la impronta Katrina.','Consultar',NULL,NULL,5),
  ('sandwiches','Lomo al Champiñón','Lomo al Champiñón','Con papas españolas y salsa de champiñones.','Consultar',NULL,NULL,6),
  ('sandwiches','Milanesa Napolitana para 2 personas','Milanesa Napolitana para 2 personas','Milanesa napolitana para compartir entre dos.','Consultar',NULL,NULL,7),
  ('compartir','Tacos del Norte','Tacos del Norte','Carne, pollo o mixtos. 3 tortillas (1p) · 6 tortillas (2p).','$12.000 / $20.000',NULL,NULL,0),
  ('compartir','Charly Gratinado','Charly Gratinado','Pan de miga, ternera, verdura, queso y papas. Chico / Grande.','$18.000 / $30.000',NULL,NULL,1),
  ('compartir','Nachos del Desierto','Nachos del Desierto','Con dip de guacamole y cheddar.','Consultar',NULL,NULL,2),
  ('compartir','Picada Fría','Picada Fría','Salame, jamón, muzarella, cheddar, aceitunas, papas Lays y maní. 2p.','$20.000',NULL,NULL,3),
  ('compartir','Picada Caliente','Picada Caliente','Milanesa, aros de cebolla, papas, bastones de muzarella, crock, salchicha envuelta + 3 dips. 2p / 4p.','$25.000 / $35.000',NULL,NULL,4),
  ('bajon','Hot Dog Callejero','Hot Dog Callejero','Simple, como en la calle.','$5.000',NULL,NULL,0),
  ('bajon','Hot Dog Frontera','Hot Dog Frontera','Especial de la casa.','$6.000',NULL,NULL,1),
  ('bajon','Hot Dog Encamisado','Hot Dog Encamisado','Envuelto en huevo con queso gratinado.','$8.000',NULL,NULL,2),
  ('bajon','Papas con Cheddar & Bacon','Papas con Cheddar & Bacon',NULL,'$9.000',NULL,NULL,3),
  ('bajon','Papas Clásicas','Papas Clásicas',NULL,'$7.000',NULL,NULL,4),
  ('bajon','Salchipapas','Salchipapas',NULL,'$7.000',NULL,NULL,5),
  ('bajon','Pollo Frito con Papas','Pollo Frito con Papas',NULL,'$10.000',NULL,NULL,6),
  ('postres','Mini Cheesecake de Frutos Rojos','Mini Cheesecake de Frutos Rojos',NULL,'Consultar',NULL,NULL,0),
  ('postres','Mini Cheesecake de Maracuyá','Mini Cheesecake de Maracuyá',NULL,'Consultar',NULL,NULL,1),
  ('postres','Postre Oreo','Postre Oreo',NULL,'Consultar',NULL,NULL,2),
  ('postres','Tiramisú','Tiramisú',NULL,'Consultar',NULL,NULL,3),
  ('barra','Daiquiri de Frutilla','Daiquiri de Frutilla','O combinado con durazno. Sin alcohol.','Consultar',NULL,NULL,0),
  ('barra','Daiquiri en Rocas','Daiquiri en Rocas',NULL,'Consultar',NULL,NULL,1),
  ('barra','Frozen / Daiquiri','Frozen / Daiquiri',NULL,'Consultar',NULL,NULL,2),
  ('barra','Sex on the Beach','Sex on the Beach',NULL,'Consultar',NULL,NULL,3),
  ('barra','Jarra de Gancia','Jarra de Gancia',NULL,'Consultar',NULL,NULL,4),
  ('barra','Trago con Menta','Trago con Menta',NULL,'Consultar',NULL,NULL,5),
  ('barra','Trago de Naranja','Trago de Naranja',NULL,'Consultar',NULL,NULL,6),
  ('barra','Trago Doble Colado','Trago Doble Colado',NULL,'Consultar',NULL,NULL,7),
  ('barra','Licor de Pepino','Licor de Pepino',NULL,'Consultar',NULL,NULL,8),
  ('barra','Limonada de Frutos Rojos','Limonada de Frutos Rojos',NULL,'Consultar',NULL,NULL,9)
) AS v(category_id, photo_key, name, description, price, price_whole, price_half, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.menu_items LIMIT 1);
